parameters:
  - name: project
    type: string
    default: ""
steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack ${{ parameters.project }}"
    inputs:
      command: pack
      packagesToPack: "src/${{ parameters.project }}/${{ parameters.project }}.csproj"
      configuration: $(buildConfiguration)
      packDirectory: "$(Build.StagingDirectory)/${{ parameters.project }}"
      buildProperties: "Version=$(Build.BuildNumber)"
